CARGO_TRACKING_FIELDS = [
    'uni_in_shipment',
    'shipper',
    'destination',
    'vehicle_type',
    'date_of_dispatch',
    'current_station',
    'remaining_distance',
    'number_of_container_or_wagon',
    'arrival_date',
    'brand',
    'gross_weight',
    'net_weight',
    'places_number',
]