"""remaining_distance from str to float

Revision ID: 0718e04562b6
Revises: 13ef23a8f2f4
Create Date: 2025-07-16 11:02:03.029068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0718e04562b6'
down_revision: Union[str, Sequence[str], None] = '13ef23a8f2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('cargo_tracking', 'remaining_distance',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    op.execute('ALTER TABLE cargo_tracking ALTER COLUMN remaining_distance TYPE FLOAT USING remaining_distance::float')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cargo_tracking', 'remaining_distance',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
