"""added cargo tracking model

Revision ID: 13ef23a8f2f4
Revises: 30f2dc10cbf8
Create Date: 2025-07-15 14:21:51.191761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ef23a8f2f4'
down_revision: Union[str, Sequence[str], None] = '30f2dc10cbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo_tracking',
    sa.Column('uni_in_shipment', sa.String(), nullable=False),
    sa.Column('shipper', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('date_of_dispatch', sa.Date(), nullable=False),
    sa.Column('current_station', sa.String(), nullable=True),
    sa.Column('remaining_distance', sa.String(), nullable=True),
    sa.Column('number_of_container_or_wagon', sa.String(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('gross_weight', sa.Float(), nullable=False),
    sa.Column('net_weight', sa.Float(), nullable=False),
    sa.Column('places_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cargo_tracking')
    # ### end Alembic commands ###
