"""added file_type to chemistry_file model

Revision ID: c17823f12fac
Revises: 56cb561d8cae
Create Date: 2025-08-11 09:56:04.719897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17823f12fac'
down_revision: Union[str, Sequence[str], None] = '56cb561d8cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemistry_files', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemistry_files', 'file_type')
    # ### end Alembic commands ###
